export const QUERY_ALL_CANDIDATES_SUCCESS = 'QUERY_ALL_CANDIDATES_SUCCESS';
export const QUERY_ALL_CANDIDATES_ERROR = 'QUERY_ALL_CANDIDATES_ERROR';

export const ADD_CANDIDATE_SUCCESS = 'ADD_CANDIDATE_SUCCESS';
export const ADD_CANDIDATE_ERROR = 'ADD_CANDIDATE_ERROR';