export const START_EXAMINATION = 'START_EXAMINATION';
export const START_EXAMINATION_SUCCESS = 'START_EXAMINATION_SUCCESS';
export const START_EXAMINATION_ERROR = 'START_EXAMINATION_ERROR';

export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const SUBMIT_ANSWER_ERROR = 'SUBMIT_ANSWER_ERROR';