export const START_EXAM = 'START_EXAM';
export const START_EXAM_SUCCESS = 'START_EXAM_SUCCESS';
export const START_EXAM_ERROR = 'START_EXAM_ERROR';

export const QUERY_ALL_PROMPTS = 'QUERY_ALL_PROMPTS';
export const QUERY_ALL_PROMPTS_SUCCESS = 'QUERY_ALL_PROMPTS_SUCCESS';
export const QUERY_ALL_PROMPTS_ERROR = 'QUERY_ALL_PROMPTS_ERROR';

export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const SUBMIT_ANSWER_ERROR = 'SUBMIT_ANSWER_ERROR';