// API Action Types :
export const START_EXAM_SUCCESS = 'START_EXAM_SUCCESS';
export const START_EXAM_ERROR = 'START_EXAM_ERROR';

export const QUERY_EXAM_SUCCESS = 'QUERY_EXAM_SUCCESS';
export const QUERY_EXAM_ERROR = 'QUERY_EXAM_ERROR';

export const QUERY_ALL_PROMPTS_SUCCESS = 'QUERY_ALL_PROMPTS_SUCCESS';
export const QUERY_ALL_PROMPTS_ERROR = 'QUERY_ALL_PROMPTS_ERROR';

export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const SUBMIT_ANSWER_ERROR = 'SUBMIT_ANSWER_ERROR';

export const FINISH_EXAM_SUCCESS = 'FINISH_EXAM_SUCCESS';
export const FINISH_EXAM_ERROR = 'FINISH_EXAM_ERROR';

// ROUTELESS Action Types:
export const SELECT_NEXT_PROMPT = 'SELECT_NEXT_PROMPT';
export const SET_TIME_REMAINING = 'SET_TIME_REMAINING';
