export const QUERY_ALL_PROMPTS_SUCCESS = 'QUERY_ALL_PROMPTS_SUCCESS';
export const QUERY_ALL_PROMPTS_ERROR = 'QUERY_ALL_PROMPTS_ERROR';

export const QUERY_ALL_PROMPTS_LIST_SUCCESS = 'QUERY_ALL_PROMPTS_LIST_SUCCESS';
export const QUERY_ALL_PROMPTS_LIST_ERROR = 'QUERY_ALL_PROMPTS_LIST_ERROR';

export const ADD_PROMPT_SUCCESS = 'ADD_PROMPT_SUCCESS';
export const ADD_PROMPT_ERROR = 'ADD_PROMPT_ERROR';

export const EDIT_PROMPT_SUCCESS = 'EDIT_PROMPT_SUCCESS';
export const EDIT_PROMPT_ERROR = 'EDIT_PROMPT_ERROR';

export const DELETE_PROMPT_SUCCESS = 'DELETE_PROMPT_SUCCESS';
export const DELETE_PROMPT_ERROR = 'DELETE_PROMPT_ERROR';


export const EDIT_PROMPT = 'EDIT_PROMPT';
export const SAVE_EDIT_PROMPT = 'SAVE_EDIT_PROMPT';